export enum UserRole {
  ADMIN = 'ADMIN',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  DEPARTMENT_EXPERT = 'DEPARTMENT_EXPERT',
  DISSEMINATION_HEAD = 'DISSEMINATION_HEAD',
  DISSEMINATION_EXPERT = 'DISSEMINATION_EXPERT',
  DEPUTY_DIRECTOR = 'DEPUTY_DIRECTOR',
  PORTAL_USER = 'PORTAL_USER',
}

export const USER_ROLE_RANK: Record<UserRole, number> = {
  [UserRole.ADMIN]: 0,
  [UserRole.DEPARTMENT_HEAD]: 1,
  [UserRole.DEPARTMENT_EXPERT]: 2,
  [UserRole.DISSEMINATION_HEAD]: 3,
  [UserRole.DISSEMINATION_EXPERT]: 4,
  [UserRole.DEPUTY_DIRECTOR]: 5,
  [UserRole.PORTAL_USER]: 6,
};
